logging:
    level: error
    level.org.springframework.data: debug
    file: pergunta2.log
server:
    port: 8082
spring:
    data:
        mongodb:
            database: socio-torcedor
            host: 104.198.77.67
            port: 27019
    application:
       name: socio-torcedor-service
    freemarker:
       enabled: false   
    thymeleaf:
       cache: false
       prefix: classpath:/templates/
zuulserver:
  ribbon:
    listOfServers: http://localhost:8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/